import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NavBar from "@/components/nav-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it_IT" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-svh grid-rows-[20px_1fr] items-center justify-items-center font-sans antialiased`}
      >
        <nav className="row-start-1">
          <NavBar />
        </nav>
        <main className="row-start-2 flex items-center gap-[32px] p-2 sm:items-start">
          {children}
        </main>

        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
